version: '3.3'
services:
  web:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php_73
    depends_on:
      - db
    volumes:
      - ./php:/var/www/html/
    ports:
      - 8100:80
  db:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: timetable
      MYSQL_USER: devuser
      MYSQL_PASSWORD: pass
    ports:
      - 6033:3309
    volumes:
      - mysql-data:/var/lib/mysql
  phpmyadmin:
    container_name: phpadmin    
    image: phpmyadmin/phpmyadmin
    restart: always
    environment: 
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
volumes:
  mysql-data:   
